language: python
os: linux
dist: jammy
python:
  - "3.11"  # Specify the Python version you are using

install:
  - gem install webrick
  - pip install -r requirements.txt  # Install dependencies
  - pip install black
  - pip install flake8
  - pip install coveralls

before_script:
  - python manage.py migrate

script:
  - black . --check
  - flake8 . --max-line-length=88
  - coverage run --source=mysite,polls manage.py test

after_script:
  - coveralls

deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_ACCESS_SECRET
    region: "us-west-2"
    app: "swe1-app"
    env: "swe1-app-env"
    bucket_name: "elasticbeanstalk-us-west-2-452681582606"
    on:
      branch: main


