language: python
python:
  - "3.11"  # Specify the Python version you are using
install:
  - pip install -r requirements.txt  # Install dependencies
before_script:
  - python manage.py migrate
script:
  - python manage.py test  # Run your tests

